### ISSUE TITLE
Support for Cookie Clicker 2.031

### ISSUE THREAD

**Issue by smurfhunter** [staticvariablejames/InsugarTrading#1]
The game does not have info for the new stock added in the new version of the game and also fails to launch.

**Comment by staticvariablejames** [comment]
It's on the works
Expanding the database for the new building will take longer, though.

**Comment by staticvariablejames** [comment]
The mod works with Cookie Clicker v2.031 and I computed datasets for bank levels 1 and 10 (which should be most cases).

Datasets for other bank levels will be added over time.
