### ISSUE TITLE
Line on graphs for certain quantile thresholds

### ISSUE THREAD

**Issue by sewcioj** [staticvariablejames/InsugarTrading#2]
The way I use this mod is that I buy stocks below certain threshold, and sell above another threshold (currently 20-80%), and I see one possible, minor "quality of life" enhancement related to that - it could be useful to see additional lines on value graphs for certain quantiles, preferably defineable by user.

Other than that - awesome mod, very helpful :)

**Comment by staticvariablejames** [comment]
It's live!

**Comment by sewcioj** [comment]
I like that you also added values for these quantiles, nice touch :)
