### ISSUE TITLE
CCSE dependency warning

### ISSUE THREAD

**Issue by moussetc** [staticvariablejames/InsugarTrading#5]
Hi, and thanks for the mod :)

When I load the mod, whether by bookmarklet or the CC Mod Manager browser plugin, there's the following warning: 
> Insugar Trading version 1.3.3 is meant for CCSE version 2.021.  Loading a different version may cause errors.  Do you still want to load Insugar Trading?

Indeed, the current CCSE version is 2.023. It's be nice to get rid of that warning.

**Comment by staticvariablejames** [comment]
Fixed!
