### ISSUE TITLE
Crashes cookie clicker

### ISSUE THREAD

**Issue by smurfhunter** [staticvariablejames/InsugarTrading#6]
The moment this mod loads on HTTPS cookie clicker, the current version (2.031) results in most of cookie clicker freezing. I can still interact with some things, like the stocks, but my cookie count, wrinklers, etc, freeze up.

**Comment by staticvariablejames** [comment]
I could not reproduce here. Which website are you using? Which mods are you loading together with Insugar Trading?

I am aware that there are conflicts with Cookie Monster; most mods do, actually. You must load Cookie Monster _after_ Insugar Trading.

**Comment by smurfhunter** [comment]
Oh that is so weird. I guess it's a CCSE and cookie monster conflict then? But I guess that's not an issue with this mod. Thanks!
